### ISSUE TITLE
Auto-loading of more icons fails for tall browser windows

### ISSUE THREAD

**Issue by jamesscottbrown** [duerrsimon/bioicons#3]
When doing a search query, or clicking on the name of a category, 3 rows of icons are displayed.

If I open a full-height browser window on my desktop, there is a gap between the last row of images and the bottom of this page, and this prevents the auto-loading of images from working - there is no way for me to see the remaining images.

However, if I reduce the height of the browser window, this triggers auto-loading, and scrolling then loads more images.

**Comment by duerrsimon** [comment]
Thanks for flagging this. What's your browser and your screen resolution so that I can reproduce?

**Comment by jamesscottbrown** [comment]
My outer window size is 1920 x 2160 (one half of a 4K screen); my inner window size is 1920 x 2025.

This happens is both Firefox and Chromium

**Comment by duerrsimon** [comment]
I implemented an easy fix by preloading double the amount of icons at the beginning. Does that work for you?

**Comment by jamesscottbrown** [comment]
Yes, this solves the problem for me (though it still occurs under the more unusual circumstance of using a full-screen browser window on a 4K monitor in portrait orientation).

**Comment by duerrsimon** [comment]
great. I'll see if you can make the infinite scrolling function "smarter" to account for this if I have time.
4K in portrait certainly is an edge case haha.
